# Build Stage
FROM golang:1.24 AS builder
WORKDIR /app

# Cache dependencies
COPY go.mod go.sum ./
RUN go mod download

# Build
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o scheduler_bin ./scheduler/main.go

# Runtime Stage (Distroless for security and size)
FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/scheduler_bin /scheduler
EXPOSE 50051 2112
CMD ["/scheduler"]
