# Build Stage
FROM golang:1.24 AS builder
WORKDIR /app

COPY go.mod go.sum ./
RUN go mod download

COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -o worker_bin ./worker/main.go

# Runtime Stage
FROM gcr.io/distroless/static-debian12
COPY --from=builder /app/worker_bin /worker
# No ports exposed for worker (it's a client)
CMD ["/worker"]
