// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.21.12
// source: proto/democritus.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Worker sends this to register
type WorkerRegistration struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"` // Unique ID (e.g. Hostname or UUID)
	Port          int32                  `protobuf:"varint,2,opt,name=port,proto3" json:"port,omitempty"`                        // Port the worker is listening on (if needed later)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerRegistration) Reset() {
	*x = WorkerRegistration{}
	mi := &file_proto_democritus_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerRegistration) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerRegistration) ProtoMessage() {}

func (x *WorkerRegistration) ProtoReflect() protoreflect.Message {
	mi := &file_proto_democritus_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerRegistration.ProtoReflect.Descriptor instead.
func (*WorkerRegistration) Descriptor() ([]byte, []int) {
	return file_proto_democritus_proto_rawDescGZIP(), []int{0}
}

func (x *WorkerRegistration) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

func (x *WorkerRegistration) GetPort() int32 {
	if x != nil {
		return x.Port
	}
	return 0
}

// Server replies with status
type RegistrationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegistrationStatus) Reset() {
	*x = RegistrationStatus{}
	mi := &file_proto_democritus_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegistrationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegistrationStatus) ProtoMessage() {}

func (x *RegistrationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_proto_democritus_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegistrationStatus.ProtoReflect.Descriptor instead.
func (*RegistrationStatus) Descriptor() ([]byte, []int) {
	return file_proto_democritus_proto_rawDescGZIP(), []int{1}
}

func (x *RegistrationStatus) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *RegistrationStatus) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Worker identifies itself to ask for a task
type WorkerID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WorkerId      string                 `protobuf:"bytes,1,opt,name=worker_id,json=workerId,proto3" json:"worker_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkerID) Reset() {
	*x = WorkerID{}
	mi := &file_proto_democritus_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkerID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkerID) ProtoMessage() {}

func (x *WorkerID) ProtoReflect() protoreflect.Message {
	mi := &file_proto_democritus_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkerID.ProtoReflect.Descriptor instead.
func (*WorkerID) Descriptor() ([]byte, []int) {
	return file_proto_democritus_proto_rawDescGZIP(), []int{2}
}

func (x *WorkerID) GetWorkerId() string {
	if x != nil {
		return x.WorkerId
	}
	return ""
}

// The core "Physics" payload
type TaskPayload struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	TaskId         string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`                          // Unique Task ID
	Seed           int64                  `protobuf:"varint,2,opt,name=seed,proto3" json:"seed,omitempty"`                                           // Seed for reproducible RNG (Science requirement!)
	IterationCount int64                  `protobuf:"varint,3,opt,name=iteration_count,json=iterationCount,proto3" json:"iteration_count,omitempty"` // How many steps in the random walk?
	SimulationType string                 `protobuf:"bytes,4,opt,name=simulation_type,json=simulationType,proto3" json:"simulation_type,omitempty"`  // e.g., "random_walk_3d"
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TaskPayload) Reset() {
	*x = TaskPayload{}
	mi := &file_proto_democritus_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskPayload) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskPayload) ProtoMessage() {}

func (x *TaskPayload) ProtoReflect() protoreflect.Message {
	mi := &file_proto_democritus_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskPayload.ProtoReflect.Descriptor instead.
func (*TaskPayload) Descriptor() ([]byte, []int) {
	return file_proto_democritus_proto_rawDescGZIP(), []int{3}
}

func (x *TaskPayload) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskPayload) GetSeed() int64 {
	if x != nil {
		return x.Seed
	}
	return 0
}

func (x *TaskPayload) GetIterationCount() int64 {
	if x != nil {
		return x.IterationCount
	}
	return 0
}

func (x *TaskPayload) GetSimulationType() string {
	if x != nil {
		return x.SimulationType
	}
	return ""
}

// The result calculation
type TaskResult struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	TaskId           string                 `protobuf:"bytes,1,opt,name=task_id,json=taskId,proto3" json:"task_id,omitempty"`
	FinalCoordinates []float64              `protobuf:"fixed64,2,rep,packed,name=final_coordinates,json=finalCoordinates,proto3" json:"final_coordinates,omitempty"` // x, y, z (3D support)
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *TaskResult) Reset() {
	*x = TaskResult{}
	mi := &file_proto_democritus_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TaskResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TaskResult) ProtoMessage() {}

func (x *TaskResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_democritus_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TaskResult.ProtoReflect.Descriptor instead.
func (*TaskResult) Descriptor() ([]byte, []int) {
	return file_proto_democritus_proto_rawDescGZIP(), []int{4}
}

func (x *TaskResult) GetTaskId() string {
	if x != nil {
		return x.TaskId
	}
	return ""
}

func (x *TaskResult) GetFinalCoordinates() []float64 {
	if x != nil {
		return x.FinalCoordinates
	}
	return nil
}

// Acknowledgment
type Ack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Received      bool                   `protobuf:"varint,1,opt,name=received,proto3" json:"received,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_proto_democritus_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_proto_democritus_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_proto_democritus_proto_rawDescGZIP(), []int{5}
}

func (x *Ack) GetReceived() bool {
	if x != nil {
		return x.Received
	}
	return false
}

var File_proto_democritus_proto protoreflect.FileDescriptor

const file_proto_democritus_proto_rawDesc = "" +
	"\n" +
	"\x16proto/democritus.proto\x12\n" +
	"democritus\"E\n" +
	"\x12WorkerRegistration\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\x12\x12\n" +
	"\x04port\x18\x02 \x01(\x05R\x04port\"H\n" +
	"\x12RegistrationStatus\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"'\n" +
	"\bWorkerID\x12\x1b\n" +
	"\tworker_id\x18\x01 \x01(\tR\bworkerId\"\x8c\x01\n" +
	"\vTaskPayload\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12\x12\n" +
	"\x04seed\x18\x02 \x01(\x03R\x04seed\x12'\n" +
	"\x0fiteration_count\x18\x03 \x01(\x03R\x0eiterationCount\x12'\n" +
	"\x0fsimulation_type\x18\x04 \x01(\tR\x0esimulationType\"R\n" +
	"\n" +
	"TaskResult\x12\x17\n" +
	"\atask_id\x18\x01 \x01(\tR\x06taskId\x12+\n" +
	"\x11final_coordinates\x18\x02 \x03(\x01R\x10finalCoordinates\"!\n" +
	"\x03Ack\x12\x1a\n" +
	"\breceived\x18\x01 \x01(\bR\breceived2\xda\x01\n" +
	"\x13DemocritusScheduler\x12P\n" +
	"\x0eRegisterWorker\x12\x1e.democritus.WorkerRegistration\x1a\x1e.democritus.RegistrationStatus\x128\n" +
	"\aGetTask\x12\x14.democritus.WorkerID\x1a\x17.democritus.TaskPayload\x127\n" +
	"\fSubmitResult\x12\x16.democritus.TaskResult\x1a\x0f.democritus.AckB+Z)github.com/parthbhanti22/democritus/protob\x06proto3"

var (
	file_proto_democritus_proto_rawDescOnce sync.Once
	file_proto_democritus_proto_rawDescData []byte
)

func file_proto_democritus_proto_rawDescGZIP() []byte {
	file_proto_democritus_proto_rawDescOnce.Do(func() {
		file_proto_democritus_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_democritus_proto_rawDesc), len(file_proto_democritus_proto_rawDesc)))
	})
	return file_proto_democritus_proto_rawDescData
}

var file_proto_democritus_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_democritus_proto_goTypes = []any{
	(*WorkerRegistration)(nil), // 0: democritus.WorkerRegistration
	(*RegistrationStatus)(nil), // 1: democritus.RegistrationStatus
	(*WorkerID)(nil),           // 2: democritus.WorkerID
	(*TaskPayload)(nil),        // 3: democritus.TaskPayload
	(*TaskResult)(nil),         // 4: democritus.TaskResult
	(*Ack)(nil),                // 5: democritus.Ack
}
var file_proto_democritus_proto_depIdxs = []int32{
	0, // 0: democritus.DemocritusScheduler.RegisterWorker:input_type -> democritus.WorkerRegistration
	2, // 1: democritus.DemocritusScheduler.GetTask:input_type -> democritus.WorkerID
	4, // 2: democritus.DemocritusScheduler.SubmitResult:input_type -> democritus.TaskResult
	1, // 3: democritus.DemocritusScheduler.RegisterWorker:output_type -> democritus.RegistrationStatus
	3, // 4: democritus.DemocritusScheduler.GetTask:output_type -> democritus.TaskPayload
	5, // 5: democritus.DemocritusScheduler.SubmitResult:output_type -> democritus.Ack
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_democritus_proto_init() }
func file_proto_democritus_proto_init() {
	if File_proto_democritus_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_democritus_proto_rawDesc), len(file_proto_democritus_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_democritus_proto_goTypes,
		DependencyIndexes: file_proto_democritus_proto_depIdxs,
		MessageInfos:      file_proto_democritus_proto_msgTypes,
	}.Build()
	File_proto_democritus_proto = out.File
	file_proto_democritus_proto_goTypes = nil
	file_proto_democritus_proto_depIdxs = nil
}
