// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.0
// - protoc             v3.21.12
// source: proto/democritus.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DemocritusScheduler_RegisterWorker_FullMethodName = "/democritus.DemocritusScheduler/RegisterWorker"
	DemocritusScheduler_GetTask_FullMethodName        = "/democritus.DemocritusScheduler/GetTask"
	DemocritusScheduler_SubmitResult_FullMethodName   = "/democritus.DemocritusScheduler/SubmitResult"
)

// DemocritusSchedulerClient is the client API for DemocritusScheduler service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// The DemocritusScheduler service definition.
type DemocritusSchedulerClient interface {
	// RPC 1 RegisterWorker: Worker calls this to tell the server "I am alive".
	RegisterWorker(ctx context.Context, in *WorkerRegistration, opts ...grpc.CallOption) (*RegistrationStatus, error)
	// RPC 2 GetTask: Worker asks "Do you have work for me?".
	GetTask(ctx context.Context, in *WorkerID, opts ...grpc.CallOption) (*TaskPayload, error)
	// RPC 3 SubmitResult: Worker gives back the answer.
	SubmitResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Ack, error)
}

type democritusSchedulerClient struct {
	cc grpc.ClientConnInterface
}

func NewDemocritusSchedulerClient(cc grpc.ClientConnInterface) DemocritusSchedulerClient {
	return &democritusSchedulerClient{cc}
}

func (c *democritusSchedulerClient) RegisterWorker(ctx context.Context, in *WorkerRegistration, opts ...grpc.CallOption) (*RegistrationStatus, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegistrationStatus)
	err := c.cc.Invoke(ctx, DemocritusScheduler_RegisterWorker_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *democritusSchedulerClient) GetTask(ctx context.Context, in *WorkerID, opts ...grpc.CallOption) (*TaskPayload, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TaskPayload)
	err := c.cc.Invoke(ctx, DemocritusScheduler_GetTask_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *democritusSchedulerClient) SubmitResult(ctx context.Context, in *TaskResult, opts ...grpc.CallOption) (*Ack, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Ack)
	err := c.cc.Invoke(ctx, DemocritusScheduler_SubmitResult_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DemocritusSchedulerServer is the server API for DemocritusScheduler service.
// All implementations must embed UnimplementedDemocritusSchedulerServer
// for forward compatibility.
//
// The DemocritusScheduler service definition.
type DemocritusSchedulerServer interface {
	// RPC 1 RegisterWorker: Worker calls this to tell the server "I am alive".
	RegisterWorker(context.Context, *WorkerRegistration) (*RegistrationStatus, error)
	// RPC 2 GetTask: Worker asks "Do you have work for me?".
	GetTask(context.Context, *WorkerID) (*TaskPayload, error)
	// RPC 3 SubmitResult: Worker gives back the answer.
	SubmitResult(context.Context, *TaskResult) (*Ack, error)
	mustEmbedUnimplementedDemocritusSchedulerServer()
}

// UnimplementedDemocritusSchedulerServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDemocritusSchedulerServer struct{}

func (UnimplementedDemocritusSchedulerServer) RegisterWorker(context.Context, *WorkerRegistration) (*RegistrationStatus, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterWorker not implemented")
}
func (UnimplementedDemocritusSchedulerServer) GetTask(context.Context, *WorkerID) (*TaskPayload, error) {
	return nil, status.Error(codes.Unimplemented, "method GetTask not implemented")
}
func (UnimplementedDemocritusSchedulerServer) SubmitResult(context.Context, *TaskResult) (*Ack, error) {
	return nil, status.Error(codes.Unimplemented, "method SubmitResult not implemented")
}
func (UnimplementedDemocritusSchedulerServer) mustEmbedUnimplementedDemocritusSchedulerServer() {}
func (UnimplementedDemocritusSchedulerServer) testEmbeddedByValue()                             {}

// UnsafeDemocritusSchedulerServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DemocritusSchedulerServer will
// result in compilation errors.
type UnsafeDemocritusSchedulerServer interface {
	mustEmbedUnimplementedDemocritusSchedulerServer()
}

func RegisterDemocritusSchedulerServer(s grpc.ServiceRegistrar, srv DemocritusSchedulerServer) {
	// If the following call panics, it indicates UnimplementedDemocritusSchedulerServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DemocritusScheduler_ServiceDesc, srv)
}

func _DemocritusScheduler_RegisterWorker_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerRegistration)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemocritusSchedulerServer).RegisterWorker(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemocritusScheduler_RegisterWorker_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemocritusSchedulerServer).RegisterWorker(ctx, req.(*WorkerRegistration))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemocritusScheduler_GetTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WorkerID)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemocritusSchedulerServer).GetTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemocritusScheduler_GetTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemocritusSchedulerServer).GetTask(ctx, req.(*WorkerID))
	}
	return interceptor(ctx, in, info, handler)
}

func _DemocritusScheduler_SubmitResult_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TaskResult)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DemocritusSchedulerServer).SubmitResult(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DemocritusScheduler_SubmitResult_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DemocritusSchedulerServer).SubmitResult(ctx, req.(*TaskResult))
	}
	return interceptor(ctx, in, info, handler)
}

// DemocritusScheduler_ServiceDesc is the grpc.ServiceDesc for DemocritusScheduler service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DemocritusScheduler_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "democritus.DemocritusScheduler",
	HandlerType: (*DemocritusSchedulerServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterWorker",
			Handler:    _DemocritusScheduler_RegisterWorker_Handler,
		},
		{
			MethodName: "GetTask",
			Handler:    _DemocritusScheduler_GetTask_Handler,
		},
		{
			MethodName: "SubmitResult",
			Handler:    _DemocritusScheduler_SubmitResult_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/democritus.proto",
}
